### PR TITLE
Enable an option to purge all of '/etc/cron.d'

### PR DESCRIPTION
**Pull request by solarkennedy**
Primary: @hashbrowncipher 

I think we have finally arrived. We are at the point where I think we, at yelp, can purge all the cron jobs.

Here is my audit on a subset of our servers:

```
    955  /etc/cron.d/sysstat
    955  /etc/cron.d/.placeholder
    939  /etc/cron.d/mdadm
    131  /etc/cron.d/php5
     30  /etc/cron.d/mcelog.dpkg-bak
     12  /etc/cron.d/mcelog
     12  /etc/cron.d/atop
      5  /etc/cron.d/cacti
      4  /etc/cron.d/apt-mirror.dpkg-dist
      2  /etc/cron.d/restart-nagios
      2  /etc/cron.d/restart-nagdash-collector
      2  /etc/cron.d/request-tracker4
      2  /etc/cron.d/mysql_status
      2  /etc/cron.d/MegaSAS.log
      1  /etc/cron.d/top_30_trac_pages
      1  /etc/cron.d/syslog-ng
      1  /etc/cron.d/sensu_server_chaos_monkey
      1  /etc/cron.d/sensu_dashboard_chaos_monkey
      1  /etc/cron.d/sensu_api_chaos_monkey
      1  /etc/cron.d/s3ked
      1  /etc/cron.d/redis_sentinel_chaos_monkey
      1  /etc/cron.d/redis_chaos_monkey
      1  /etc/cron.d/rabbitmq_chaos_monkey
      1  /etc/cron.d/puppetmaster-cleanup-templates
      1  /etc/cron.d/puppetmaster-clean-certs
      1  /etc/cron.d/nameomatic
      1  /etc/cron.d/mysql-zrm-new-testrtbackup
      1  /etc/cron.d/mrjob_monitoring
      1  /etc/cron.d/mrjob_collect_emr_stats
      1  /etc/cron.d/iam_admin
      1  /etc/cron.d/git-mirror
      1  /etc/cron.d/generate_ssh_known_hosts
      1  /etc/cron.d/email_old_acks
      1  /etc/cron.d/dmits_iproute2_git_commit
      1  /etc/cron.d/cloudinit-updates
      1  /etc/cron.d/bchess-test
      1  /etc/cron.d/amdump
      1  /etc/cron.d/alert_counts
```

Let's purge this crap!

### CODE REVIEW

**Comment by hashbrowncipher** [comment]
hmm.  This would basically enshrine a policy that OS packages cannot use /etc/cron.d (unless whitelisted).  I imagine this will be surprising for someone expecting certain functionality from their packages.  As an example, atop restarts nightly in order to rotate its logfile.  It could be quite painful for someone who expects this default behavior if they installed atop, forget to add to the whitelist (they totally will), and experience broken behavior.

It's just a bit too silent for my tastes.  That said, I would be happy to enable purging for a short period of time to remove all of the cruft you've identified.

Could you clarify your goal?  Is it to create a new policy?  Is it to clean up existing infrastructure?

**Comment by solarkennedy** [comment]
I agree that would be surprising, that is why it defaults to false.

At Yelp I'm suggesting a new policy, and that is to have cronjobs that are not configured in puppet.

Are you suggesting I should turn it on for only a short while, let the cruft clear, and then turn off the purging?

**Comment by hashbrowncipher** [comment]
Yes, I think such a policy would be pretty surprising, even at Yelp.  Most people don't inspect the contents of packages before installing them, so I think we'll break functionality for those people, in a possibly painful way (probably involving disks, simultaneously filling).  I'm willing to be convinced otherwise.

At Puppetconf, @jolynch and I discussed the possibility of Puppet resource types capable of purging files, but which automatically ignored files installed by packages.  I think that's what we want here, because ideally Yelp would have a policy of "You may have any cronjob you like, so long as it comes from Puppet or a package".  I've sketched such a possibility as pseudocode [in a gist](https://gist.github.com/hashbrowncipher/4b107ff0d518d521be20)

**Comment by solarkennedy** [comment]
Closing for now, I agree this is a bit aggressive.

**Pull request closed without merging**
