### PR TITLE
Relax alert_after to be one unit of the check_every

### PR DESCRIPTION
**Pull request by solarkennedy**
This check can be flappy. Yes, the check file age *can* inherently be used to be unflappy, but in practice there are at least two situations I can think of that make this alert a bit noisier than it could be:
* On first boot after a reboot alerts will fire and resolve right away, because the cron hasn't been running while the machine is off
* Sometimes puppet can have a race between removing *or* adding sudo rules, etc, which cause a blip.

Setting this alert_after should remove them and give these 1 unit of time to figure themselves out.

### CODE REVIEW

**Comment by hashbrowncipher** [comment]
For this to work, I think we need to give the cronjob at least one full interval to run.  Since the check_every is 20% of the cron interval (iirc), I think this will only work for staleness checks with staleness_threshold >= 5 cron intervals?

**Comment by solarkennedy** [comment]
Er, right. Hmm. Let me rethink.

**Comment by solarkennedy** [comment]
Ok @hashbrowncipher, I've set it to be just the threshold seconds itself, and as long as nobody sets a threshold shorter than the cron interval, then this should work.

**Comment by hashbrowncipher** [comment]
As currently implemented, if I have a check on a backup that should always be no more than two days stale, I won't get alerted for it until it is four days stale.  Do I have my math right there?

The only way I can make this math work out correctly in my head is if we change `${threshold_s}` on line 20 to instead be `${check_every}`. But it seems weird for the check to be CRITICAL for most of its existence, which is what this would imply.

**Comment by solarkennedy** [comment]
Yea, I think there might be two different kind of expectations here. If you have a backup job that runs once a week, and the box is down for a week, and comes back up, do you expect an alert?

When *do* you expect an alert? One week later?

**Comment by ydgholz** [comment]
Personally I'd expect not to get an alert for something which is supposed to run every hour, or once a day, until the host has been up long enough for the thing to run.

How about a configuration option, to consider the host being off as a valid reason for the job not to have run?

**Comment by solarkennedy** [comment]
Hmm. I think anyone who is using this check for something like "making sure a backup runs once a day" or something, needs to be aware of the limitations. (it doesn't work if the host is down)

That use case really needs to be using an alternate mechanism.

Maybe we need a "smarter" check file age that inspects the incoming staleness threshold and returns "OK" if the `uptime` is below the threshold *or* the file is newer than the threshold. @hashbrowncipher  would that be ok with you?

**Comment by hashbrowncipher** [comment]
That would feel a lot better to me.

**Comment by solarkennedy** [comment]
I'm going to close this and open a different PR for that.

**Comment by solarkennedy** [comment]
Closed in favor of #13

**Pull request closed without merging**
